Translate to turkish
notifo-io/notifo pull request #220
Opened 2024-02-24 21:05 UTC by alibildir

translated to Turkish language. If browser language is Turkish it changes automatically.

2024-02-24 21:08 UTC, SebastianStehle commented
Awesome. I think there are 2 things that I would like to change:

1. I think it would be good to have a fallback system for the frontend. Because if we add new texts we would not necessarily have everything in turkish.

2. Can also be done later: An option to override the language, independent from the browser setting.

2024-02-25 07:21 UTC, alibildir commented
i want to help you. i can do some solutions in a few week. Also if you need add a word or sentences in resx or .ts please add it to .tr. files in english i will check your every commit. maybe you can request code review to me if you need

2024-02-25 09:16 UTC, SebastianStehle commented
Resx files already have the fallback handling, but not the frontend. But I can also do that.

2024-02-25 12:06 UTC, SebastianStehle requested changes

2024-02-25 12:06 UTC, SebastianStehle commented on backend/src/Notifo.Domain/Apps/App.cs
> +    private static readonly ReadonlyList<string> DefaultLanguages = ReadonlyList.Create("en", "tr");
This needs to be reverted.

2024-02-25 12:59 UTC, merged